language: node_js
node_js:
- v6
- v5
- v4
- '0.12'
notifications:
  slack:
    secure: o55xqLdxJSsZ8APwj8pv9FX2cdnNyOhOoe3CDileShWKYdyzjJvul5/Xz/HNENWHBMEkubggTUOcVJhihJiF1an3rqAWUUsAph0p8aL7MPuSjrgCqauqKTktCsZ2Sq+4inHZ9Nz2p6v203A/YsKA7AT19O1hrszUlyUmu48ELBHhg97M86EULNGaMwnRlX458A7kxghETGeXPOZYs7Esruyx2+hFtlCEMaNgstMa8un0YSKwJjpV+NW4cNnWeBmxoh4hDmrNIU8BaE/+0AC6SCMp9h2cmcAiC4N0J+Fj7MW53DYnX4PDzy2MHxueVPBZMwzXtxkOTbZZx/DdbU9Tjijs27OoI2SbsL/Ac3+3c4apjD1a8WdsWx6+KugUwLOIbEO10qTrqPxEymhZCpQ8PXwWjd7xO1RqC8GxamcQ3R/34Nt6QA1fwleob06IU0JBWPmsDYiSnsuUVfQjOjFw4yFu2dgnXUmJYhohsTcFoBZLnAnlT3MyiYJl9iRpr9eU9Ye6MeLvmuYbhs/+9lG6zYITFn5oM99s84YxKm84HOYzzW8kxDkNqlUwN4HQ1L/gQm10bRl3BDYSDEzapzRN6hvh5c/TSyNwMs+e+EmX52loPYnl1HfWlqaNcGsRlhBuCeRNGYyHJKvM299kYUi+pIrhGWDhcnS7rQw3yxoP8os=
